In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Sindhu\Downloads\tips.csv")
df

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34  1.66    Male     No   Sun  Dinner     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68  3.31    Male     No   Sun  Dinner     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

## 1. Calculate the average total bill and average tip for Sundays

In [8]:
avg_total_bill = df[df['day'] == 'Sun']['total_bill'].mean()
avg_tip = df[df['day'] == 'Sun']['tip'].mean()
print("Average total bill on Sunday:", avg_total_bill)
print("Average tip on Sunday:", avg_tip)

Average total bill on Sunday: 21.41
Average tip on Sunday: 3.2551315789473687

## 2. Find the highest tip amount given by a female customer during dinner on a Sunday.

In [4]:
filtered = df[(df['sex'] == 'Female') & (df['time'] == 'Dinner') & (df['day'] == 'Sun')]
highest_tip = filtered['tip'].max()

print("Highest tip given by a female customer during dinner on Sunday:", highest_tip)

Highest tip given by a female customer during dinner on Sunday: 5.2

## 3. Create a new column named `tip_pct` that stores the tip percentage of the total bill.

In [5]:
df['tip_pct'] = (df['tip'] / df['total_bill']) * 100
df

,Unnamed: 0,total_bill,tip,sex,smoker,day,time,size,tip_pct
0,0,16.99,1.01,Female,No,Sun,Dinner,2,5.944673
1,1,10.34,1.66,Male,No,Sun,Dinner,3,16.054159
2,2,21.01,3.50,Male,No,Sun,Dinner,3,16.658734
3,3,23.68,3.31,Male,No,Sun,Dinner,2,13.978041
4,4,24.59,3.61,Female,No,Sun,Dinner,4,14.680765
...,...,...,...,...,...,...,...,...,...
239,239,29.03,5.92,Male,No,Sat,Dinner,3,20.392697
240,240,27.18,2.00,Female,Yes,Sat,Dinner,2,7.358352
241,241,22.67,2.00,Male,Yes,Sat,Dinner,2,8.822232
242,242,17.82,1.75,Male,No,Sat,Dinner,2,9.820426
243,243,18.78,3.00,Female,No,Thur,Dinner,2,15.974441

## 4. Create a new column named `bill_per_person` by dividing *total_bill* by the number of people (*size*).

In [6]:
df['bill_per_person']=(df['size']/df['total_bill']) * 100
df

,Unnamed: 0,total_bill,tip,sex,smoker,day,time,size,tip_pct,bill_per_person
0,0,16.99,1.01,Female,No,Sun,Dinner,2,5.944673,11.771630
1,1,10.34,1.66,Male,No,Sun,Dinner,3,16.054159,29.013540
2,2,21.01,3.50,Male,No,Sun,Dinner,3,16.658734,14.278915
3,3,23.68,3.31,Male,No,Sun,Dinner,2,13.978041,8.445946
4,4,24.59,3.61,Female,No,Sun,Dinner,4,14.680765,16.266775
...,...,...,...,...,...,...,...,...,...,...
239,239,29.03,5.92,Male,No,Sat,Dinner,3,20.392697,10.334137
240,240,27.18,2.00,Female,Yes,Sat,Dinner,2,7.358352,7.358352
241,241,22.67,2.00,Male,Yes,Sat,Dinner,2,8.822232,8.822232
242,242,17.82,1.75,Male,No,Sat,Dinner,2,9.820426,11.223345
243,243,18.78,3.00,Female,No,Thur,Dinner,2,15.974441,10.649627

## 5. Add a new column called `date` containing dates starting from today’s date (assign one date per row).

In [9]:
from datetime import date, timedelta
today = date.today()
dates = [today + timedelta(days = i) for i in range(len(df))]
df["date"] = dates
print(df.head(4))

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size    tip_pct  \
0           0       16.99  1.01  Female     No  Sun  Dinner     2   5.944673
1           1       10.34  1.66    Male     No  Sun  Dinner     3  16.054159
2           2       21.01  3.50    Male     No  Sun  Dinner     3  16.658734
3           3       23.68  3.31    Male     No  Sun  Dinner     2  13.978041

   bill_per_person        date
0        11.771630  2025-08-29
1        29.013540  2025-08-30
2        14.278915  2025-08-31
3         8.445946  2025-09-01

## 6. From the date column, extract the month number and store it in a new column called month.

In [10]:
df['date'] = pd.to_datetime(df['date'])
df['month'] = df['date'].dt.month
print(df.head())

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size    tip_pct  \
0           0       16.99  1.01  Female     No  Sun  Dinner     2   5.944673
1           1       10.34  1.66    Male     No  Sun  Dinner     3  16.054159
2           2       21.01  3.50    Male     No  Sun  Dinner     3  16.658734
3           3       23.68  3.31    Male     No  Sun  Dinner     2  13.978041
4           4       24.59  3.61  Female     No  Sun  Dinner     4  14.680765

   bill_per_person       date  month
0        11.771630 2025-08-29      8
1        29.013540 2025-08-30      8
2        14.278915 2025-08-31      8
3         8.445946 2025-09-01      9
4        16.266775 2025-09-02      9

## 7. Standardize the values in the `sex` column by converting them to lowercase and then capitalizing the first letter (e.g., "male" → "Male")

In [11]:
df['sex'] = df['sex'].str.lower().str.capitalize()
print(df['sex'].unique())

['Female' 'Male']

## 8. Create a new column named customer_type based on the number of people (size) at the table:

- Assign **"Family"** if size is 5 or more

- Assign **"Friends"** if size is 3 or 4

- Assign **"Lovers"** if size is exactly 2

- Assign **"Single"** if size is 1

In [13]:
import numpy as np
conditions = [
    (df['size'] >=5),
    (df['size'].isin([3,4])),
    (df['size'] == 2),
    (df['size'] ==1)
]
values = ['Family', 'Friends', 'Lovers', 'Single']
df['customer_type'] = np.select(conditions, values)
print(df[['size', 'customer_type']].head(10))

   size customer_type
0     2        Lovers
1     3       Friends
2     3       Friends
3     2        Lovers
4     4       Friends
5     4       Friends
6     2        Lovers
7     4       Friends
8     2        Lovers
9     2        Lovers

## 9. Filter and display only those rows where the percentage of tip (tip / total_bill × 100) is greater than 20%.

In [14]:
high_tips = df[df['tip_pct']>20]
print(high_tips.head())

    Unnamed: 0  total_bill   tip     sex smoker  day    time  size    tip_pct  \
6            6        8.77  2.00    Male     No  Sun  Dinner     2  22.805017
9            9       14.78  3.23    Male     No  Sun  Dinner     2  21.853857
14          14       14.83  3.02  Female     No  Sun  Dinner     2  20.364127
17          17       16.29  3.71    Male     No  Sun  Dinner     3  22.774708
18          18       16.97  3.50  Female     No  Sun  Dinner     3  20.624632

    bill_per_person       date  month customer_type
6         22.805017 2025-09-04      9        Lovers
9         13.531800 2025-09-07      9        Lovers
14        13.486177 2025-09-12      9        Lovers
17        18.416206 2025-09-15      9       Friends
18        17.678256 2025-09-16      9       Friends

## 10. Generate a `pivot table` that shows the average `total_bill` grouped by day (rows) and sex (columns).

In [15]:
import pandas as pd
pivot = pd.pivot_table(df, values ='total_bill', index = 'day', columns='sex', aggfunc='mean')
print(pivot)

sex      Female       Male
day
Fri   14.145556  19.857000
Sat   19.680357  20.802542
Sun   19.872222  21.887241
Thur  16.715312  18.714667

## 11. Identify and display the `outliers` in the `tip` column using the Interquartile Range (IQR) method.

In [16]:
# Step 1: Calculate Q1 (25th percentile) and Q3 (75th percentile)
Q1 = df['tip'].quantile(0.25)
Q3 = df['tip'].quantile(0.75)

# Step 2: Calculate IQR
IQR = Q3 - Q1

# Step 3: Define lower and upper bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Step 4: Filter out outliers
outliers = df[(df['tip'] < lower_bound) | (df['tip'] > upper_bound)]

print("Outliers in tip column:")
print(outliers)

Outliers in tip column:
     Unnamed: 0  total_bill    tip     sex smoker   day    time  size  \
23           23       39.42   7.58    Male     No   Sat  Dinner     4
47           47       32.40   6.00    Male     No   Sun  Dinner     4
59           59       48.27   6.73    Male     No   Sat  Dinner     4
141         141       34.30   6.70    Male     No  Thur   Lunch     6
170         170       50.81  10.00    Male    Yes   Sat  Dinner     3
183         183       23.17   6.50    Male    Yes   Sun  Dinner     4
212         212       48.33   9.00    Male     No   Sat  Dinner     4
214         214       28.17   6.50  Female    Yes   Sat  Dinner     3
239         239       29.03   5.92    Male     No   Sat  Dinner     3

       tip_pct  bill_per_person       date  month customer_type
23   19.228818        10.147133 2025-09-21      9       Friends
47   18.518519        12.345679 2025-10-15     10       Friends
59   13.942407         8.286721 2025-10-27     10       Friends
141  19.533528        17.492711 2026-01-17      1        Family
170  19.681165         5.904350 2026-02-15      2       Friends
183  28.053517        17.263703 2026-02-28      2       Friends
212  18.621974         8.276433 2026-03-29      3       Friends
214  23.074192        10.649627 2026-03-31      3       Friends
239  20.392697        10.334137 2026-04-25      4       Friends

# Numpy

## 1. Generate a NumPy array of 100 random integers between 10 and 100.
- Find the mean, median, variance, and standard deviation.

- Count how many numbers are above the mean.

In [17]:
import numpy as np
arr = np.random.randint(10, 101, size = 100)
print(arr)

[ 49  79  13  62  50  27  66  62  58  98  81  47  92  89  99  26  73  57
  70  23  18  11  36  36  28  54  39  68  68  55  16  59  36  23  81  64
  84  48  40  51  27  92  95  15  16  51  81  41  47  68  75  17  51  55
  86  81  48  80  61  58  96  20  71  87  68  73  80  89  61  85  81  92
  63 100  88  52  18  85  49  29  57  28  62  63  37  86  92  73  10  69
  13  94  71  16  35  26  75  82  17  12]

In [18]:
mean_val = np.mean(arr)
median_val = np.median(arr)
variance_val = np.var(arr)
std_dev_val = np.std(arr)
count = np.sum(arr > mean_val)
print("Mean:", mean_val)
print("Median:", median_val)
print("Variance:", variance_val)
print("Standard Deviation:", std_dev_val)
print("Count above mean:", count)

Mean: 56.86
Median: 60.0
Variance: 672.8604
Standard Deviation: 25.939552810331946
Count above mean: 55

## 2. Create a NumPy array of 20 random integers between 1 and 50.

- Replace all even numbers with -1

In [19]:
import numpy as np
arr = np.random.randint(1, 51, 20)
print("Original Array:", arr)

arr[arr %2==0] = -1
print("Modified Array:", arr)

Original Array: [17  4 41 28 13 16 49 43 22  2 33 39 44 40  5 44 16 29 37 18]
Modified Array: [17 -1 41 -1 13 -1 49 43 -1 -1 33 39 -1 -1  5 -1 -1 29 37 -1]

## 3. Update Using Indexing

- Create a NumPy array of shape (4,4) with values from 1 to 16.

- Update the first row to all 0s.

- Update the last column to all 99

In [20]:
import numpy as np
arr =np.arange(1, 17).reshape(4, 4)
print("Original Array:", arr)

Original Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

In [21]:
arr[0, :] = 0
print(arr)

[[ 0  0  0  0]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

In [22]:
arr[:, -1] = 99
print(arr)

[[ 0  0  0 99]
 [ 5  6  7 99]
 [ 9 10 11 99]
 [13 14 15 99]]

## 4.Create a NumPy array of shape (3,5) with all values initialized to 1.

- Add [1,2,3,4,5] to each row of the array using broadcasting (without a loop).

In [23]:
import numpy as np
arr = np.ones((3, 5), dtype=int)
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

In [24]:
vec = np.array([1, 2, 3, 4, 5])
result = arr+ vec
print(result)

[[2 3 4 5 6]
 [2 3 4 5 6]
 [2 3 4 5 6]]